set.seed(1)
test_that("MLESetOfEstimates", {
    est <- MLESetOfEstimates()
    expect_equal(est$nest, 0)
    
    data1     <- MLEData(y = rnorm(10000, 1, 2))
    data2     <- MLEData(y = rnorm(10000, 1, 2))
    model     <- SimpleModel("y")
    constr    <- MLEConstraints(xL = c(-1e20, 0))
    estopt1   <- MLEEstimationOptions(constr = constr, startparam = c(0, 2))
    est1      <- model$estimate(data1, estopt1)
    est2      <- model$estimate(data2)
    estimates <- MLESetOfEstimates(list(est1, est2))
    
    expect_equal(estimates$nest, 2)
    expect_is(estimates$estimates, "list")
    expect_identical(estimates$estimates[[1]], est1)
    expect_identical(estimates$estimates[[2]], est2)
    expect_is(estimates$param_list, "list")
    expect_equal(length(estimates$param_list), 2)
    expect_is(estimates$dparam_list, "list")
    expect_equal(length(estimates$dparam_list), 2)
    expect_equal(estimates$startparam_list[[1]], c(0, 2))
    expect_equal(estimates$dstartparam_list[[2]], c(0, Inf))
    
    estimates$addEstimate(est1)
    expect_equal(estimates$nest, 3)
    expect_identical(estimates$estimates[[1]], estimates$estimates[[3]])
    expect_equal(length(estimates$param_list), 3)
    expect_equal(length(estimates$dparam_list), 3)
    expect_equal(estimates$startparam_list[[3]], c(0, 2))
    expect_equal(estimates$dstartparam_list[[3]], c(log(2), Inf))
})
