library(GSLabModel)
library(NumericalDerivatives)
library(devtools)
library(testthat)
library(KnitroR)

source("../R/derivedParam.R")
source("../R/drawErrors.R")
source("../R/drawUnobservables.R")
source("../R/estimate.R")
source("../R/getDerivedParam.R")
source("../R/simulate.R")
source("../R/transformErrors.R")
source("../R/transformUnobservables.R")

source("../R/MLEConstraints/setUpperBound.R")
source("../R/MLEConstraints/setLowerBound.R")
source("../R/MLEConstraints/setFixedBound.R")
source("../R/MLEConstraints/removeBound.R")
source("../R/MLEConstraints/isConsistent.R")
source("../R/MLEConstraints/JacobianOfConstraints.R")
source("../R/MLEConstraints/MLEConstraints.R")

source("../R/MLEData.R")
source("../R/MLEModel.R")
source("../R/MLESimulationOptions.R")
source("../R/MLESetOfDatasets.R")
source("../R/MLEEstimationOptions.R")
source("../R/MLEEstimationOutput.R")

test_file("test-MLESetOfDatasets.R")
test_file("test-simulation.R")
test_file("test-ExampleModel.R")
test_file("test-MLEConstraints.R")
