library(GSLabModel)
library(NumericalDerivatives)
library(devtools)
library(testthat)
library(KnitroR)
library(SparseGrid)

source("../R/MLEModel/derivedParam.R")
source("../R/MLEModel/drawErrors.R")
source("../R/MLEModel/drawUnobservables.R")
source("../R/MLEModel/estimate.R")
source("../R/MLEModel/getDerivedParam.R")
source("../R/MLEModel/simulate.R")
source("../R/MLEModel/transformErrors.R")
source("../R/MLEModel/transformUnobservables.R")
source("../R/MLEModel/computeNodesAndWeights.R")
source("../R/MLEModel/MLEModel.R")

source("../R/MLEConstraints/setUpperBound.R")
source("../R/MLEConstraints/setLowerBound.R")
source("../R/MLEConstraints/setFixedBound.R")
source("../R/MLEConstraints/removeBound.R")
source("../R/MLEConstraints/isConsistent.R")
source("../R/MLEConstraints/JacobianOfConstraints.R")
source("../R/MLEConstraints/MLEConstraints.R")

source("../R/MLEData/MLEData.R")

source("../R/MLEEstimationOutput/MLEEstimationOutput.R")

source("../R/MLEEstimationOptions.R")
source("../R/MLESetOfDatasets.R")
source("../R/MLESetOfEstimates.R")
source("../R/MLESimulationOptions.R")

source("../R/misc.R")
source("ExampleModel.R")

test_file("test-ExampleModel.R")
test_file("test-MLEEstimationOptions.R")
test_file("test-MLEConstraints.R")
test_file("test-MLESetOfDatasets.R")
test_file("test-MLESetOfEstimates.R")
test_file("test-simulation.R")
test_file("test-misc.R")
