source("../R/derivedParam.R")
source("../R/drawErrors.R")
source("../R/drawUnobservables.R")
source("../R/estimate.R")
source("../R/getDerivedParam.R")
source("../R/simulate.R")
source("../R/transformErrors.R")
source("../R/transformUnobservables.R")

library(devtools)
library(testthat)
library(GSLabModel)
setwd("../../")
install("GSLabMLE")
library(GSLabMLE)
test_file("test-MLESetOfDatasets.R")
test_file("test-simulation.R")
test_file("test-ExampleModel.R")